version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:2.11.0-pg14
    environment:
      POSTGRES_USER: zinnia
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: zinnia_test
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U zinnia -d zinnia_test -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - timescaledb_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "63790:6379"
    healthcheck:
      test: ["CMD-SHELL","redis-cli ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  timescaledb_test_data:
